---
title: "FPR - Usoskin dataset"
author: "Fanny Perraudeau"
date: "`r Sys.Date()`"
output: 
html_document: 
fig_height: 7
fig_width: 7
toc: yes
code_folding: hide
toc_float: yes
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE)
library(edgeR)
library(limma)
library(DESeq2)
library(zinbwave)
library(BiocParallel)
library(doParallel)
library(Biobase)
library(ggplot2)
library(devtools)
```

The goal of this document is to evaluate the FPR of our method and compare it to the FPR of other methods (edgeR, DESeq2, limmavoom, MAST, scde). 

# Data
```{r data}
path = '../../datasets/usoskin/'
load(paste0(path, 'esetUsoskin.RData'))
eset=eset[rowSums(exprs(eset)>0)>=20,]
exprs(eset) <- apply(exprs(eset),2,function(x) {storage.mode(x) <- 'integer'; x})

file = paste0(path, "subsetMatrixUsoskinFPR_randomCellTypes.txt")
subsets <- read.table(file)
```

# Batch
```{r batchUsoskin}
pickingSession = factor(pData(eset)[, 'Picking sessions'])
usoskin = exprs(eset)
expit <- function(x) 1/(1+exp(-x))
logLib = log(colSums(usoskin))
pZero = colMeans(usoskin == 0)
plot(x = logLib, y = pZero, xlab = "Log library size", ylab = "Fraction of zeros",
     main = "", cex.lab = 1.5, cex.main = 1.5, bty = "l", pch = 1, cex.axis = 1.5,
     col = as.numeric(pickingSession))
m = glm(pZero ~ logLib, family = "binomial")
a = coef(m)[1]
b = coef(m)[2]
lines(x = sort(logLib),
      y = expit(a + b * sort(logLib)), lwd = 2, col = "steelblue")
m2 = glm(pZero ~ logLib + pickingSession, family = "binomial")
a = coef(m2)[1]
b = coef(m2)[2]
lines(x = sort(logLib[pickingSession == "Cold"]),
      y = expit(a + b * sort(logLib[pickingSession == "Cold"])), lwd = 2, col = 1)
a = coef(m2)[1] + coef(m2)[3]
b = coef(m2)[2]
lines(x = sort(logLib[pickingSession == "RT-1"]), 
      y = expit(a + b * sort(logLib[pickingSession == "RT-1"])), col = 2, lwd = 2)
a = coef(m2)[1] + coef(m2)[4]
lines(x = sort(logLib[pickingSession == "RT-2"]),
      y = expit(a + b * sort(logLib[pickingSession == "RT-2"])), col = 3, lwd = 2)
legend("bottomleft", c("Global", "Cold", "RT-1", "RT-2"),
       col = c("steelblue", 1:3), lty = 1, cex = 1.5)
mtext("b", at = 4, font = 2, cex = 4/3)
```

# Posterior probabilities of the ZINB-WaVE model

```{r}
cData = pData(eset)[,c('Level 3', 'Picking sessions')]
colnames(cData) = c('Level3', 'Pickingsessions')
se = SingleCellExperiment(assays = list(counts = exprs(eset)),
                          colData = cData)
colData(se)$Pickingsessions = factor(colData(se)$Pickingsessions)
colData(se)$Level3 = factor(colData(se)$Level3)
```

```{r,eval=FALSE}
library(zinbwave)
library(doParallel)
library(BiocParallel)
NCORES <- 2
registerDoParallel(NCORES)
register(DoparParam())
set.seed(8492)

print(system.time(zinb_batch <- zinbFit(se, X = '~ Pickingsessions + Level3')))
fn = 'zinb_batch.rda'
save(zinb_batch, file = fn)

print(system.time(zinb_nobatch <- zinbFit(se, X = '~ Level3')))
fn = 'zinb_nobatch.rda'
save(zinb_nobatch, file = fn)
```

```{r}
load('zinb_nobatch.rda')
weights_nobatch = computeObservationalWeights(zinb_nobatch, assay(se))
load('zinb_batch.rda')
weights_batch = computeObservationalWeights(zinb_batch, assay(se))
```

```{r histWeightsUsoskin}
ylim = c(0, 3e6)
hist(weights_batch[assay(se)==0], main = "", cex.lab = 1.5,
     xlab = "Weight", cex.axis = 1.5, ylim=ylim)
hist(weights_nobatch[assay(se)==0], add = TRUE, ylim=ylim,
     col = rgb(0.1, 0.8, 0.1, .2))
legend("topright", c("picking session + cell type",
                     "cell type"),
       fill = c(0, rgb(0.1, 0.8, 0.1, .2)), bty = "n", cex = 1.25)
mtext("c", at = -.25, font = 2, cex = 4/3)
```
```{r}
wb = c(weights_batch[assay(se)==0])
wob = c(weights_nobatch[assay(se)==0])
```

# Functions

```{r sourceEdgeR}
runEdgeR <- function(e) {
  library(edgeR)
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  design <- model.matrix(~ condition + pickingSession)
  dgel <- DGEList(exprs(e))
  dgel <- edgeR::calcNormFactors(dgel)
  dgel=estimateDisp(dgel,design)
  edger.fit <- glmFit(dgel, design)
  edger.lrt <- glmLRT(edger.fit, coef="conditionB")
  pvals <- edger.lrt$table$PValue
  padj <- p.adjust(pvals,method="BH")
  padj[is.na(padj)] <- 1
  logfc <- edger.lrt$table$logFC
  list(pvals=pvals, padj=padj, logfc = logfc)
}

```

```{r deseq2}
runDESeq2_poscounts <- function(e) {
  load_all('../../../DESeq2')
  dds <- DESeqDataSetFromMatrix(exprs(e),
                                colData=DataFrame(pData(e)),
                                design=~ condition + pickingSession)
  dds <- estimateSizeFactors(dds,type="poscounts")
  dds <- estimateDispersions(dds, minmu = 1e-3)
  dds <- nbinomWaldTest(dds, betaPrior=TRUE, modelMatrixType="standard", minmu = 1e-3)
  res <- results(dds, name="condition_B_vs_A")
  pvals <- res$pvalue
  padj <- res$padj
  #pvals[is.na(pvals)] <- 1
  #padj[is.na(padj)] <- 1
  logfc <- res$log2FoldChange
  list(pvals=pvals, padj=padj, logfc = logfc)
}
```


```{r zinbwaveEdgeR}
runZinbwaveEdgeR <- function(e){
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  design <- model.matrix(~ condition + pickingSession)
  # compute zinbwave weights
  library(zinbwave)
  zinb <- zinbFit(exprs(e), X = design, epsilon = 1e12)
  weights <- computeObservationalWeights(zinb, exprs(e))
  d <- DGEList(exprs(e))
  d <- edgeR::calcNormFactors(d)
  d$weights <- weights
  d=estimateDisp(d, design)
  fit=glmFit(d,design)
  lrt=glmWeightedF(fit,coef=2, independentFiltering = TRUE)
  pvals = lrt$table$PValue
  list(pvals = pvals, padj = lrt$table$padjFilter, logfc = lrt$table$logFC)
}
```

```{r zinbwavedeseq2}
runZinbwaveDESeq2 <- function(e){
  load_all('../../../DESeq2')
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  design <- model.matrix(~ condition + pickingSession)
  # compute zinbwave weights
  library(zinbwave)
  zinb <- zinbFit(exprs(e), X = design, epsilon = 1e12)
  weights <- computeObservationalWeights(zinb, exprs(e))
  dse <- DESeqDataSetFromMatrix(exprs(e), colData=DataFrame(pData(e)),
                                design=~ condition + pickingSession)
  dse <- estimateSizeFactors(dse, type="poscounts")
  dimnames(weights) = NULL
  assays(dse)[["weights"]] = weights
  dse <- estimateDispersions(dse, minmu = 1e-3)
  dse = nbinomWaldTest(dse, betaPrior=TRUE, useT=TRUE, df=rowSums(weights)-2, minmu = 1e-3)
  res = results(dse, name="conditionB")
  list(pvals = res$pvalue, padj = res$padj, logfc = res$log2FoldChange)
}
```

```{r}
runMAST <- function(e){
  require(MAST)
  counts <- exprs(e)
  tpm <- counts*1e6/colSums(counts)
  tpm <- log2(tpm+1)
  sca <- FromMatrix(tpm,
                    cData=data.frame(group=pData(e)$condition,
                                     pickingSession=pData(e)$pickingSession))
  
  # Adaptive thresholding from MAST vignette
  freq_expressed <- 0.2
  thres <- thresholdSCRNACountMatrix(assay(sca), nbins = 10, min_per_bin = 50,
                                     conditions = pData(e)$condition)
  #par(mfrow=c(5,4))
  #plot(thres)
  assays(sca) <- list(thresh=thres$counts_threshold, tpm=assay(sca))
  expressed_genes <- freq(sca) > freq_expressed
  sca <- sca[expressed_genes,]
  
  ngeneson <- apply(exprs(e),2,function(x) mean(x>0))
  CD <- colData(sca)
  CD$ngeneson <- ngeneson
  CD$cngeneson <- CD$ngeneson-mean(ngeneson)
  colData(sca) <- CD
  ## differential expression
  fit <- zlm(~ cngeneson + group + pickingSession, sca = sca,
             method = "bayesglm", ebayes = TRUE)
  L <- matrix(0, nrow = ncol(coef(fit, "D")))
  rownames(L) <- colnames(coef(fit, "D"))
  L["groupB",] <- 1
  lrFit <- lrTest(fit, hypothesis = L)
  pval <- lrFit[, 'hurdle', 'Pr(>Chisq)']
  padj <- p.adjust(pval, method = "BH")
  list(pvals = pval, padj = padj, logfc = NA)
}
```

```{r limmavoom}
runVoom <- function(e) {
  library(limma)
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  design <- model.matrix(~ condition + pickingSession)
  dgel <- DGEList(exprs(e))
  dgel <- edgeR::calcNormFactors(dgel)
  v <- voom(dgel,design,plot=FALSE)
  fit <- lmFit(v,design)
  fit <- eBayes(fit)
  tt <- topTable(fit,coef="conditionB",n=nrow(dgel),sort.by="none")
  pvals <- tt$P.Value
  padj <- p.adjust(pvals,method="BH")
  padj[is.na(padj)] <- 1
  list(pvals=pvals, padj=padj, logfc=tt$logFC)
}
```

```{r scde}
runSCDE <- function(e){
  require(scde)
  # calculate models
  counts = exprs(e)
  rownames(counts) = fData(e)[,1]
  o.ifm <- scde.error.models(counts = counts, groups = pData(e)$condition, n.cores = 2,
                             threshold.segmentation = TRUE,
                             save.crossfit.plots = FALSE, 
                             save.model.plots = FALSE, verbose = 0)
  
  # estimate gene expression prior
  o.prior <- scde.expression.prior(models = o.ifm, counts = exprs(e), length.out = 400, show.plot = FALSE)
  # run differential expression tests on all genes.
  ediff <- scde.expression.difference(o.ifm, exprs(e), o.prior, 
                                      groups  =  pData(e)$condition,
                                      n.randomizations  =  100,
                                      n.cores  =  2, verbose  =  0,
                                      batch=factor(pData(e)$pickingSession))
  pvals=(1-pnorm(abs(ediff[[1]]$Z)))*2
  padj=p.adjust(pvals,method="BH")
  list(pvals=pvals,padj=padj,logfc=NA)
}
```


# Results

```{r res}
algos <- list("DESeq2"          = runDESeq2_poscounts,
              "DESeq2-zinbwave" = runZinbwaveDESeq2,
              "edgeR"           = runEdgeR,
              "edgeR-zinbwave"  = runZinbwaveEdgeR,
              "limma-voom"      = runVoom,
              "MAST"            = runMAST,
              "SCDE"            = runSCDE)
namesAlgos <- names(algos)
names(namesAlgos) <- namesAlgos
nreps <- 30
```

```{r,eval=FALSE}
NCORES <- 2
registerDoParallel(NCORES)
register(DoparParam())
res <- lapply(1:nreps, function(i) {
  cat(i," ")
  eLoop <- eset[,as.numeric(subsets[i,])]
  # We remove genes with only zeros as zinbwave needs to remove these genes
  cat('Removing ', sum(rowSums(exprs(eLoop)) == 0), 
      " genes with only 0's")
  eLoop <- eLoop[rowSums(exprs(eLoop)) != 0, ]
  condition=factor(rep(c("A","B"),each=45))
  pickingSession=factor(rep(rep(c("Cold","rt1","rt2"),each=15),2))
  pData(eLoop)$condition=condition
  pData(eLoop)$pickingSession=pickingSession
  resFPR <- lapply(namesAlgos, function(n){
    print(n)
    algos[[n]](eLoop)
  })
  save(resFPR, file = sprintf('FPR_%s.rda', i))
  rm(resFPR)
  i
})
```

```{r}
res <- lapply(1:nreps, function(i) {
  load(sprintf('FPR_%s.rda', i))
  resFPR
})
```


## Boxplots

```{r}
hlp=lapply(res,function(replication){
  lapply(replication,function(method){
    pval=method$pvals
    pval[is.na(pval)]=1 #independent filtering
    mean(pval<=0.05)
  })
})

fprHat=Reduce(hlp,f=cbind)
fprHat=matrix(unlist(fprHat),nrow=length(algos),ncol=nreps,byrow=FALSE)
rownames(fprHat)=namesAlgos

boxplotData=data.frame(fpr=c(t(fprHat)),method=rep(namesAlgos,each=nreps))
```

```{r fprUsoskinHist}
boxplotData$method = as.vector(boxplotData$method)
ourcol = rep(1, length(unique(boxplotData$method)))
ourcol[c(4, 6)] = 4 #our methods in blue
ggplot(boxplotData,
       aes(x=reorder(method,fpr,median),y=fpr)) +
  geom_boxplot(outlier.colour=rgb(0,0,0,0), col = ourcol) +
  theme_bw() +
  geom_point(position = position_jitter(w = 0.1, h = 0),
             color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("") +
  scale_colour_discrete(guide="none")  + ylab("PCER") +
  geom_hline(aes(yintercept=0.05,colour="red")) +
  theme(text = element_text(size=20))
```

## Histograms of pvalues
```{r fprUsoskinPval}
library(scales)
par(mfrow=c(3,3))
hh <- sapply(1:length(res[[1]]), function(i){
  col = 'white'
  if (i %in% c(2,4)) col = 'blue'
  nn = names(algos)[i]
  hist(res[[1]][[i]]$pvals, main = nn, 
       cex.lab = 1.5, cex.axis = 1.5, cex.main = 1.5,
       xlab = 'p-values', col = alpha(col,.8),
       breaks = seq(0, 1, by = 0.05)) 
})
par(mfrow=c(1,1))
```

## Plot paper
```{r fprUsoskin,fig.width=10,fig.height=7}
par(mar = c(4.1, 4.25, 3.1, 1), bty = "l")
layout(rbind(cbind(matrix(1,3,3), matrix(2,3,3)),
             cbind(matrix(3,3,3), matrix(4:12,3,3,byrow = TRUE))))

# batch effect
pickingSession = factor(pData(eset)[, 'Picking sessions'])
usoskin = exprs(eset)
expit <- function(x) 1/(1+exp(-x))
logLib = log(colSums(usoskin))
pZero = colMeans(usoskin == 0)
plot(x = logLib, y = pZero, xlab = "Log library size", ylab = "Fraction of zeros",
     main = "", cex.lab = 1.5, cex.main = 1.5, pch = 1, cex.axis = 1.5,
     col = as.numeric(pickingSession))
m = glm(pZero ~ logLib, family = "binomial")
a = coef(m)[1]
b = coef(m)[2]
lines(x = sort(logLib),
      y = expit(a + b * sort(logLib)), lwd = 2, col = "steelblue")
m2 = glm(pZero ~ logLib + pickingSession, family = "binomial")
a = coef(m2)[1]
b = coef(m2)[2]
lines(x = sort(logLib[pickingSession == "Cold"]),
      y = expit(a + b * sort(logLib[pickingSession == "Cold"])), lwd = 2, col = 1)
a = coef(m2)[1] + coef(m2)[3]
b = coef(m2)[2]
lines(x = sort(logLib[pickingSession == "RT-1"]), 
      y = expit(a + b * sort(logLib[pickingSession == "RT-1"])), col = 2, lwd = 2)
a = coef(m2)[1] + coef(m2)[4]
lines(x = sort(logLib[pickingSession == "RT-2"]),
      y = expit(a + b * sort(logLib[pickingSession == "RT-2"])), col = 3, lwd = 2)
legend("bottomleft", c("Global", "Cold", "RT-1", "RT-2"),
       col = c("steelblue", 1:3), lty = 1, cex = 1.5)
mtext("a",padj=-1,adj=-0.1, font = 2, cex = 4/3)

# historgram post proba
ylim = c(0, 3e6)
hist(weights_batch[assay(se)==0], main = "", cex.lab = 1.5,
     xlab = "Weight", cex.axis = 1.5, ylim=ylim)
mtext("b", at=-0.2, padj = -1, font=2,cex = 4/3)
hist(weights_nobatch[assay(se)==0], add = TRUE, ylim=ylim,
     col = rgb(0.1, 0.8, 0.1, .2))
legend("topright", c("picking session + cell type",
                     "cell type"),
       fill = c(0, rgb(0.1, 0.8, 0.1, .2)), bty = "n", cex = 1.25)



# pcer = f(eps)
library(gridBase)
library(grid)
plot.new()              ## suggested by @Josh
vps <- baseViewports()
pushViewport(vps$figure) ##   I am in the space of the autocorrelation plot
vp1 <-plotViewport(c(1, 1, 1, 1)) ## create new vp with margins, you play with this values 

h <- ggplot(boxplotData,
       aes(x=reorder(method,fpr,median),y=fpr)) +
  geom_boxplot(outlier.colour=rgb(0,0,0,0), col = ourcol) +
  theme_bw() +
    geom_point(position = position_jitter(w = 0.1, h = 0),
               color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("") +
  scale_colour_discrete(guide="none") + ylab("PCER") +
  geom_hline(aes(yintercept=0.05,colour="red")) +
  theme(text = element_text(size=15))

print(h,vp = vp1)  
mtext("c" ,at=-0.15, padj = -2, font=2, cex=4/3)

# hist pvalues
hh <- sapply(1:length(res[[1]]), function(i){
  col = 'white'
  if (i %in% c(2,4)) col = 'blue'
  nn = names(algos)[i]
  if (nn =='DESeq2_poscounts') nn = 'DESeq2'
  hist(res[[1]][[i]]$pvals, main = nn,
       xlab = "p-values", cex.lab = 1.5, 
       cex.axis =  1.5, cex.main = 1.2, col = alpha(col, .8),
       breaks = seq(0, 1, by = 0.05)) 
  if (i==2) mtext("d" ,at=-0.8, padj = -2, font=2, cex=4/3)
})
```

## Supplementary figure

### Results

```{r}
library(zingeR)
library(DESeq2)
runZingerDESeq2 <- function(e){
  #load_all('../../../DESeq2/')
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  dse <- DESeqDataSetFromMatrix(exprs(e), colData=DataFrame(pData(e)), design=~ condition + pickingSession)
  dse <- estimateSizeFactors(dse, type="poscounts")
  effLogLibSize <- log(colSums(counts(dse))*(1/sizeFactors(dse)))
  designZI=model.matrix(~effLogLibSize + pickingSession)
  zeroWeights = zeroWeightsLS(counts(dse), verbose=FALSE, design=model.matrix(~condition + pickingSession), colData=colData(dse), normalization="DESeq2_pos", designZI=designZI)
  assays(dse)[["weights"]] = zeroWeights
  dse <- estimateDispersions(dse)
  dse <- nbinomWaldTest(dse, betaPrior=TRUE, useT=TRUE, df=rowSums(zeroWeights)-2)
  res <- results(dse, name="conditionB")
  list(pvals = res$pvalue, padj = res$padj, logfc = res$log2FoldChange)
}

runZingerEdgeR <- function(e){
  library(edgeR)
  condition = pData(e)$condition
  pickingSession = pData(e)$pickingSession
  design <- model.matrix(~ condition + pickingSession)
  d <- DGEList(exprs(e))
  d <- edgeR::calcNormFactors(d)
  #not adding a design matrix models the zeroes with the library size automatically
  effLogLibSize = log(d$samples$lib.size*d$samples$norm.factors)
  pickingSession = pData(e)[,"Picking sessions"]
  designZI = model.matrix(~ effLogLibSize + pickingSession)
  zeroWeights = zeroWeightsLS(d$counts, design, verbose = FALSE)
  d$weights = zeroWeights
  d=estimateDisp(d,design)
  fit <- glmFit(d, design)
  lrt = zinbwave::glmWeightedF(fit, coef=2, independentFiltering = TRUE)
  list(pvals = lrt$table$PValue, padj = lrt$table$padjFilter,
       logfc = lrt$table$logFC)
}
```

```{r}
algos <- list("DESeq2-zinger" = runZingerDESeq2,
              "edgeR-zinger"  = runZingerEdgeR)
namesAlgos <- names(algos)
names(namesAlgos) <- namesAlgos
nreps <- 30
```

```{r,eval=FALSE}
res <- lapply(1:nreps, function(i) {
  cat(i," ")
  eLoop <- eset[,as.numeric(subsets[i,])]
  # We remove genes with only zeros as zinbwave needs to remove these genes
  cat('Removing ', sum(rowSums(exprs(eLoop)) == 0), 
      " genes with only 0's")
  eLoop <- eLoop[rowSums(exprs(eLoop)) != 0, ]
  condition=factor(rep(c("A","B"),each=45))
  pickingSession=factor(rep(rep(c("Cold","rt1","rt2"),each=15),2))
  pData(eLoop)$condition=condition
  pData(eLoop)$pickingSession=pickingSession
  resFPR <- lapply(namesAlgos, function(n){
    print(n)
    algos[[n]](eLoop)
  })
  save(resFPR, file = sprintf('FPR_%s_zinger.rda', i))
  rm(resFPR)
  i
})
```

### Plot
```{r}
algos <- list("DESeq2"          = runDESeq2_poscounts,
              "DESeq2-zinbwave" = runZinbwaveDESeq2,
              "edgeR"           = runEdgeR,
              "edgeR-zinbwave"  = runZinbwaveEdgeR,
              "limma-voom"      = runVoom,
              "MAST"            = runMAST,
              "SCDE"            = runSCDE,
              "DESeq2-zingeR"   = runZingerDESeq2,
              "edgeR-zingeR"    = runZingerEdgeR)
namesAlgos <- names(algos)
names(namesAlgos) <- namesAlgos

res <- lapply(1:nreps, function(i) {
  load(sprintf('FPR_%s.rda', i))
  res = resFPR
  load(sprintf('FPR_%s_zinger.rda', i))
  c(res, resFPR)
})

hlp=lapply(res,function(replication){
  lapply(replication,function(method){
    pval=method$pvals
    pval[is.na(pval)]=1 #independent filtering
    mean(pval<=0.05)
  })
})

fprHat=Reduce(hlp,f=cbind)
fprHat=matrix(unlist(fprHat),nrow=length(algos),ncol=nreps,byrow=FALSE)
rownames(fprHat)=namesAlgos

boxplotData=data.frame(fpr=c(t(fprHat)),method=rep(namesAlgos,each=nreps))
boxplotData$method = as.vector(boxplotData$method)
ourcol = rep(1, length(unique(boxplotData$method)))
ourcol[c(4, 5, 7, 8)] = 4 #our methods in blue
```

```{r fprUsoskinSupp,fig.width=10,fig.height=5}
library(gridBase)
library(grid)
par(mar = c(4.1, 4.25, 4.1, 1), bty = "l")
layout(cbind(matrix(1,3,3), matrix(2:10,3,3,byrow = TRUE)))
plot.new()              ## suggested by @Josh
vps <- baseViewports()
pushViewport(vps$figure) ##   I am in the space of the autocorrelation plot
vp1 <-plotViewport(c(1, 1, 1, 1)) ## create new vp with margins, you play with this values 
h <- ggplot(boxplotData,
       aes(x=reorder(method,fpr,median),y=fpr)) +
  geom_boxplot(outlier.colour=rgb(0,0,0,0), col = ourcol) +
  theme_bw() +
  geom_point(position = position_jitter(w = 0.1, h = 0),
             color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("") +
  scale_colour_discrete(guide="none")  + ylab("PCER") +
  geom_hline(aes(yintercept=0.05,colour="red")) +
  theme(text = element_text(size=20))
print(h,vp = vp1)  
mtext("a" ,at=-0.15, padj = -2, font=2, cex=4/3)

hh <- sapply(1:length(res[[1]]), function(i){
  col = 'white'
  if (i %in% c(2,4,8,9)) col = 'blue'
  nn = names(algos)[i]
  if (nn =='DESeq2_poscounts') nn = 'DESeq2'
  hist(res[[1]][[i]]$pvals, main = nn,
       xlab = "p-values", cex.lab = 1.5, 
       cex.axis =  1.5, cex.main = 1.2, col = alpha(col, .8),
       breaks = seq(0, 1, by = 0.05)) 
  if (i==1) mtext("b" ,at=-0.8, padj = -2, font=2, cex=4/3)
})

```

```{r fprUsoskinSuppNoZinger,fig.width=10,fig.height=5}
library(gridBase)
library(grid)
par(mar = c(4.1, 4.25, 4.1, 1), bty = "l")
layout(cbind(matrix(1,3,3), matrix(2:10,3,3,byrow = TRUE)))
plot.new()              ## suggested by @Josh
vps <- baseViewports()
pushViewport(vps$figure) ##   I am in the space of the autocorrelation plot
vp1 <-plotViewport(c(1, 1, 1, 1)) ## create new vp with margins, you play with this values 
boxplotData = boxplotData[!grepl('zingeR', boxplotData$method), ]
ourcol = c(1,1,1,4,1,4,1)
h <- ggplot(boxplotData,
       aes(x=reorder(method,fpr,median),y=fpr)) +
  geom_boxplot(outlier.colour=rgb(0,0,0,0), col = ourcol) +
  theme_bw() +
  geom_point(position = position_jitter(w = 0.1, h = 0),
             color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("") +
  scale_colour_discrete(guide="none")  + ylab("PCER") +
  geom_hline(aes(yintercept=0.05,colour="red")) +
  theme(text = element_text(size=20))
print(h,vp = vp1)  

hh <- sapply(1:7, function(i){
  col = 'white'
  if (i %in% c(2,4)) col = 'blue'
  nn = names(algos)[i]
  if (nn =='DESeq2_poscounts') nn = 'DESeq2'
  hist(res[[1]][[i]]$pvals, main = nn,
       xlab = "p-values", cex.lab = 1.5, 
       cex.axis =  1.5, cex.main = 1.2, col = alpha(col, .8),
       breaks = seq(0, 1, by = 0.05)) 
})
```

# sessionInfo
```{r}
sessionInfo()
```
