---
title: "Compare DE methods for 10X genomics"
author: "Fanny Perraudeau"
date: "`r Sys.Date()`"
output: 
html_document: 
fig_height: 7
fig_width: 7
toc: yes
code_folding: hide
toc_float: yes
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=FALSE, error=FALSE, message=FALSE, warning=TRUE)
library(SingleCellExperiment)
```


```{r loadobject}
loadNamespace("Seurat")
load("../seurat_tuto/pbmc_tutorial.Robj")
pbmc
```

```{r}
# use raw data as input for zinbwave but keep only non filtered cells
# and most variable genes indentified by seurat
keepcells = colnames(pbmc@data)
counts = pbmc@raw.data[, keepcells]
# zinbwave does not want dgTMatrix as input
counts = as.matrix(counts)
counts = counts[rowSums(counts) > 0, ]

# coldata
current.cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7)
new.cluster.ids <- c("CD4 T cells", "CD14+ Monocytes", "B cells", "CD8 T cells", "FCGR3A+ Monocytes", "NK cells", "Dendritic cells", "Megakaryocytes")
seuratNames <- plyr::mapvalues(x = pbmc@ident,
                               from = current.cluster.ids,
                               to = new.cluster.ids)

cData = data.frame(seuratFactor = pbmc@ident,
                   seuratVector = as.integer(pbmc@ident),
                   seuratNames = as.vector(seuratNames))
rownames(cData) = colnames(counts)

# rowdata
rData = data.frame(seuratVarGenes = rownames(counts) %in% pbmc@var.genes)
rownames(rData) = rownames(counts)

# create sce object
core = SingleCellExperiment(assays = list(counts = counts),
                            colData = cData, rowData = rData)
core
```

```{r save}
unloadNamespace("Seurat")
save(core, file = 'core.rda')
```
