---
title: "Seurat - Guided Clustering Tutorial"
output:
  html_document:
    theme: united
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---
***

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE,
  cache.lazy = FALSE,
  tidy = TRUE
)
```

### Setup the Seurat Object

```{r}
library(Seurat)
load("pbmc3k_subCD4.Rda")
```

# Find discriminating markers

```{r}
tcell.markers <- FindMarkers(object = pbmc,
                             ident.1 = 0,
                             ident.2 = 1,
                             genes.use = rownames(pbmc@raw.data),
                             thresh.use = 0,
                             test.use = "bimod",
                             min.pct = 0, 
                             min.diff.pct = -Inf,
                             print.bar = TRUE,
                             only.pos = FALSE,
                             max.cells.per.ident = Inf, 
                             random.seed = 1,
                             latent.vars = "nUMI",
                             min.cells = 0 )
```


```{r restore}
library(dplyr)
head(tcell.markers, 2)
length(unique(rownames(pbmc@raw.data)))
length(unique(rownames(tcell.markers)))
tcell.markers$gene = rownames(tcell.markers)
topgenes = tcell.markers %>% top_n(20, -p_val)
topgenes
```
```{r}
FeaturePlot(object = pbmc, features.plot = c("IL32", "S100A4"),
            
            cols.use = c("green", "blue"))
```


```{r}
FeaturePlot(object = pbmc, features.plot = c("S100A4", "CCR7"),
            cols.use = c("green", "blue"))
```

```{r}
write.csv(tcell.markers, file = 'tcellmarkers_seurat.csv')
```

