---
title: "Evaluate FPR on 10x Genomics PBMC dataset"
author: "Fanny Perraudeau"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_height: 7
    fig_width: 7
    toc: yes
    code_folding: hide
    toc_float: yes
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE)
library(DESeq2)
library(edgeR)
library(limma)
library(zinbwave)
library(genefilter)
library(BiocParallel)
library(doParallel)
library(Biobase)
library(ggplot2)
source('../../functionsToZinbwavePackage.R')
```

```{r}
NCORES <- 2
registerDoParallel(NCORES)
register(DoparParam())
```

The goal of this document is to evaluate the FPR of our method and compare it to the FPR of other methods (edgeR, DESeq2, limmavoom, MAST, scde) on 10x-genomics data 3k PMBCs.

# Functions

```{r sourceEdgeR}
runEdgeR <- function(e) {
  library(edgeR)
  condition = pData(e)$condition
  design <- model.matrix(~ condition)
  dgel <- DGEList(exprs(e))
  dgel <- edgeR::calcNormFactors(dgel)
  dgel=estimateDisp(dgel,design)
  edger.fit <- glmFit(dgel, design)
  edger.lrt <- glmLRT(edger.fit, coef="conditionB")
  pvals <- edger.lrt$table$PValue
  padj <- p.adjust(pvals,method="BH")
  padj[is.na(padj)] <- 1
  logfc <- edger.lrt$table$logFC
  list(pvals=pvals, padj=padj, logfc = logfc)
}

```

```{r deseq2}
runDESeq2_poscounts <- function(e) {
  library(DESeq2)
  dds <- DESeqDataSetFromMatrix(exprs(e),
                                colData=DataFrame(pData(e)),
                                design=~ condition)
  dds <- estimateSizeFactors(dds,type="poscounts")
  dds <- estimateDispersions(dds)
  dds <- nbinomWaldTest(dds, betaPrior=TRUE, modelMatrixType="standard")
  res <- results(dds, name="condition_B_vs_A")
  pvals <- res$pvalue
  padj <- res$padj
  pvals[is.na(pvals)] <- 1
  padj[is.na(padj)] <- 1
  logfc <- res$log2FoldChange
  list(pvals=pvals, padj=padj, logfc = logfc)
}
```

```{r sourceEdgeRzingeR}
# code from zingeRPaper-master/singleCellPaper/case/fpr/runScriptsUsoskin_pickingSession.R
runEdgeREMLibSize=function(e){
  library(edgeR)
  library(genefilter)
  condition = pData(e)$condition
  design <- model.matrix(~ condition)
  d <- DGEList(exprs(e))
  d <- edgeR::calcNormFactors(d)
  #not adding a design matrix models the zeroes with the library size automatically
  effLogLibSize = log(d$samples$lib.size*d$samples$norm.factors)
  designZI = model.matrix(~ effLogLibSize)
  zeroWeights = zeroWeightsLS(d$counts, design, verbose = FALSE)
  d$weights = zeroWeights
  d=estimateDisp(d,design)
  fit <- glmFit(d, design)
  lrt = glmWeightedF(fit, coef=2, independentFiltering = TRUE)
  list(pvals = lrt$table$PValue, padj = lrt$table$padjFilter,
       logfc = lrt$table$logFC)
}
```

```{r zingerdeseq2}
runDESeq2Zero <- function(e){
  library(DESeq2) ; library(genefilter)
  condition = pData(e)$condition
  dse <- DESeqDataSetFromMatrix(exprs(e), colData=DataFrame(pData(e)),
                                design=~ condition)
  dse <- estimateSizeFactors(dse, type="poscounts")
  effLogLibSize <- log(colSums(counts(dse))*(1/sizeFactors(dse)))
  designZI=model.matrix(~effLogLibSize)
  zeroWeights = zeroWeightsLS(counts(dse), verbose=FALSE,
                              design=model.matrix(~condition),
                              colData=colData(dse), normalization="DESeq2_pos",
                              designZI=designZI)
  assays(dse)[["weights"]] = zeroWeights
  dse <- estimateDispersions(dse)
  dse <- nbinomWaldTest(dse, betaPrior=TRUE, modelMatrixType="standard")
  res <- results(dse, name="condition_B_vs_A")
  baseMean=unname(rowMeans(sweep(counts(dse),2,1/sizeFactors(dse),FUN="*")))
  pvalDesZero = 2*(1-pt(abs(res$stat),df=rowSums(zeroWeights)-2))
  padjusted = pvalueAdjustment_kvdb(pValue=pvalDesZero,filter=baseMean,alpha=0.05)
  list(pvals=pvalDesZero,padj=padjusted$padj,logfc=res$log2FoldChange)
}
```

```{r zinbwaveEdgeR}
runZinbwaveEdgeR <- function(e){
  condition = pData(e)$condition
  design <- model.matrix(~ condition)
  # compute zinbwave weights
  library(zinbwave)
  zinb <- zinbFit(exprs(e), X = design, epsilon = 1e12)
  weights <- computeZinbwaveWeights(zinb, exprs(e))
  # use zingeR-edgeR
  d <- DGEList(exprs(e))
  d <- edgeR::calcNormFactors(d)
  d$weights <- weights
  d=estimateDisp(d, design)
  fit=glmFit(d,design)
  lrt=glmWeightedF(fit,coef=2, independentFiltering = TRUE)
  pvals = lrt$table$PValue
  list(pvals = pvals, padj = lrt$table$padjFilter, logfc = lrt$table$logFC)
}
```

```{r zinbwavedeseq2}
runZinbwaveDESeq2 <- function(e){
  condition = pData(e)$condition
  design <- model.matrix(~ condition)
  # compute zinbwave weights
  library(zinbwave)
  zinb <- zinbFit(exprs(e), X = design, epsilon = 1e12)
  weights <- computeZinbwaveWeights(zinb, exprs(e))
  # use zingeR-DESeq2
  dse <- DESeqDataSetFromMatrix(exprs(e),
                                colData=DataFrame(pData(e)),
                                design=~ condition)
  dse <- estimateSizeFactors(dse, type="poscounts")
  dimnames(weights) = NULL
  assays(dse)[["weights"]] = weights
  dse <- estimateDispersions(dse)
  dse = nbinomWaldTest(dse, betaPrior=TRUE, useT=TRUE, df=rowSums(weights)-2)
  resultsNames(dse)
  res = results(dse, name="conditionB")
  list(pvals = res$pvalue, padj = res$padj, logfc = res$log2FoldChange)
}
```

```{r}
runMAST <- function(e){
  require(MAST)
  counts <- exprs(e)
  tpm <- counts*1e6/colSums(counts)
  tpm <- log2(tpm+1)
  sca <- FromMatrix(tpm,cData=data.frame(group=pData(e)$condition))
  
  # Adaptive thresholding from MAST vignette for MAIT analysis
  freq_expressed <- 0.2
  thres <- thresholdSCRNACountMatrix(assay(sca), nbins = 300,
                                     conditions = pData(e)$condition)
  #par(mfrow=c(5,4))
  #plot(thres)
  assays(sca) <- list(thresh=thres$counts_threshold, tpm=assay(sca))
  expressed_genes <- freq(sca) > freq_expressed
  sca <- sca[expressed_genes,]

  ngeneson <- apply(exprs(e),2,function(x) mean(x>0))
  CD <- colData(sca)
  CD$ngeneson <- ngeneson
  CD$cngeneson <- CD$ngeneson-mean(ngeneson)
  colData(sca) <- CD
  ## differential expression
  fit <- zlm(~ cngeneson + group, sca = sca,
             method = "bayesglm", ebayes = TRUE)
  L <- matrix(0, nrow = ncol(coef(fit, "D")))
  rownames(L) <- colnames(coef(fit, "D"))
  L["groupB",] <- 1
  lrFit <- lrTest(fit, hypothesis = L)
  pval <- lrFit[, 'hurdle', 'Pr(>Chisq)']
  padj <- p.adjust(pval, method = "BH")
  list(pvals = pval, padj = padj, logfc = NA)
}
```

```{r limmavoom}
runVoom <- function(e) {
  library(limma)
  condition = pData(e)$condition
  design <- model.matrix(~ condition)
  dgel <- DGEList(exprs(e))
  dgel <- edgeR::calcNormFactors(dgel)
  v <- voom(dgel,design,plot=FALSE)
  fit <- lmFit(v,design)
  fit <- eBayes(fit)
  tt <- topTable(fit,coef="conditionB",n=nrow(dgel),sort.by="none")
  pvals <- tt$P.Value
  padj <- p.adjust(pvals,method="BH")
  padj[is.na(padj)] <- 1
  list(pvals=pvals, padj=padj, logfc=tt$logFC)
}
```

```{r}
runDESeq2 <- function(e, retDDS=FALSE) {
  library(DESeq2)
  dds <- DESeqDataSetFromMatrix(exprs(e), DataFrame(pData(e)), ~ condition)
  dds <- DESeq(dds,betaPrior=TRUE,quiet=TRUE)
  res <- results(dds)
  beta <- res$log2FoldChange
  pvals <- res$pvalue
  padj <- res$padj
  pvals[is.na(pvals)] <- 1
  padj[is.na(padj)] <- 1
  list(pvals=pvals, padj=padj, logfc=NA)
}
```

```{r scde}
runSCDE <- function(e){
  require(scde)
  # calculate models
  counts = exprs(e)
  rownames(counts) = fData(e)[,1]
  o.ifm <- scde.error.models(counts = counts, groups = pData(e)$condition, n.cores = 1,
                             threshold.segmentation = TRUE,
                             save.crossfit.plots = FALSE, 
                             save.model.plots = FALSE, verbose = 0)
  
  # estimate gene expression prior
  o.prior <- scde.expression.prior(models = o.ifm, counts = exprs(e), length.out = 400, show.plot = FALSE)
  # run differential expression tests on all genes.
  ediff <- scde.expression.difference(o.ifm, exprs(e), o.prior, 
                                      groups  =  pData(e)$condition,
                                      n.randomizations  =  100,
                                      n.cores  =  2, verbose  =  0,
                                    batch=factor(pData(e)$pickingSession))
  pvals=(1-pnorm(abs(ediff$Z)))*2
  padj=p.adjust(pvals,method="BH")
  list(pvals=pvals,padj=padj,logfc=NA)
}
```


# Data

```{r data}
load('../../realdata/data/core.rda')
core
ncells = 45
nreps = 30

subsets = sapply(1:nreps, function(i){
  set.seed(i)
  c1 = sample(ncol(core), ncells, replace = FALSE)
  remaining = seq_len(ncol(core))
  remaining = remaining[!remaining %in% c1]
  c2 = sample(remaining, ncells, replace = FALSE)
  stopifnot(sum(c1 %in% c2) == 0 )
  stopifnot(sum(c2 %in% c1) == 0 )
  c(c1, c2)
})
subsets = as.data.frame(t(subsets))
```

# Results

```{r res}
algos <- list("DESeq2"          = runDESeq2,
              "DESeq2_poscounts"= runDESeq2_poscounts,
              "DESeq2-zingeR"   = runDESeq2Zero,
              "DESeq2-zinbwave" = runZinbwaveDESeq2,
              "edgeR"           = runEdgeR,
              "edgeR-zingeR"    = runEdgeREMLibSize,
              "edgeR-zinbwave"  = runZinbwaveEdgeR,
              "limma-voom"      = runVoom,
              "MAST"            = runMAST,
              "SCDE"            = runSCDE)
namesAlgos <- names(algos)
names(namesAlgos) <- namesAlgos
```

```{r,eval=FALSE}
eset = as(core, 'ExpressionSet')
res <- lapply(1:nreps, function(i) {
    cat(i," ")
    eLoop <- eset[,as.numeric(subsets[i,])]
    ngenes = sum(rowSums(exprs(eLoop) > 0) < 5)
    cat(sprintf("Removing %s genes with only 0's", ngenes))
    # remove genes with too many zeros
    eLoop <- eLoop[rowSums(exprs(eLoop) > 0) > 4, ]
    condition = factor(rep(c("A", "B"), each = 45))
    pData(eLoop)$condition = condition
    resFPR <- lapply(namesAlgos, function(n){
      print(n)
      algos[[n]](eLoop)
    })
    save(resFPR, file = sprintf('FPR_.%srda', i))
    rm(resFPR)
    i
})
```

```{r}
res <- lapply(1:nreps, function(i) {
  load(sprintf('FPR_.%srda', i))
  resFPR
})
```

## Boxplots
```{r prepBoxplots}
hlp=lapply(res,function(replication){
  lapply(replication,function(method){
    pval=method$pvals
    pval[is.na(pval)]=1 #independent filtering
    mean(pval<=0.05)
  })
})

fprHat=Reduce(hlp,f=cbind)
fprHat=matrix(unlist(fprHat),nrow=length(algos),ncol=nreps,byrow=FALSE)
rownames(fprHat)=namesAlgos

boxplotData=data.frame(fpr=c(t(fprHat)),method=rep(namesAlgos,each=nreps))
```

```{r fpr10x}
boxplotData = boxplotData[!grepl('zingeR', boxplotData$method),]
ourcol = rep(1, length(unique(boxplotData$method)))
ourcol[c(2, 4)] = 4 #our methods in blue
ggplot(boxplotData,
       aes(x=reorder(method,fpr,median),y=fpr)) +
  geom_boxplot(outlier.colour=rgb(0,0,0,0), col = ourcol) +
  theme_bw() +
    geom_point(position = position_jitter(w = 0.1, h = 0),
               color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("") +
  scale_colour_discrete(guide="none") + ylab("PCER") +
  geom_hline(aes(yintercept=0.05,colour="red")) +
  theme(text = element_text(size=20))
```

## Histograms of pvalues
```{r fpr10xPval}
library(scales)
keep = !grepl('zingeR', names(res[[1]]))
idx = 1:length(res[[1]])
idx = idx[keep]
par(mfrow=c(3,3))
hh <- sapply(idx, function(i){
  col = 'white'
  if (i %in% c(4,7)) col = 'blue'
  hist(res[[1]][[i]]$pvals, main = names(algos)[i],
       xlab = "p-values", cex.lab = 1.5, 
       cex.axis =  1.5, cex.main = 1.5, col = alpha(col, .8),
       breaks = seq(0, 1, by = 0.05)) 
})
par(mfrow=c(1,1))
```

# sessionInfo
```{r}
sessionInfo()
```